---
title: "What You Can Do"
output: html_document
---
##
##
##
#### Speak For The Earth

The biggest way that you can make a difference is to be an influence on the people around you. Be the change that you want to see! Social scientists have found that when one person makes a sustainability-oriented decision, other people do too. You can also exercise your rights and urge local governments and companies to make the system-wide changes that are needed.


#### Make Your Home Energy Efficient

Having an energy efficient home can save you energy and money! You can invest in energy efficient technology like LED light bulbs, sealing your doors, or a low flow showerhead. You can also do simple tasks such as unplugging unused electronics, washing laundry on cool setting, and taking shorter showers. It takes a lot of energy to pump and heat water.


#### Start A [Compost Pile](http://www.planitdiy.com/inspiration/in-kids/a-compost-bin-project-for-the-kids/)

Compost is decayed organic matter such as egg shells, leaves, fruit peels, and grains. Once thrown together and left alone for nature to work its magic, the organic matter turns into a nutrient rich soil. Composting has several benefits including cutting down on greenhouse gases! Compost piles turn into a natural fertilizer which many local farmers markets will collect. This allows us to cut back on the use of chemical fertilizers, helps control weeds, and minimizes the need for watering. 

#### Service Your Car

Tasks as simple as maintaining your tire pressure and having a clean air filter can boost your MPGs, therefore saving on gas and cutting down on emissions.


#### Reduce Waste

There are countless ways that you can reduce your daily waste! To name just a few: Use reusable grocery bags, coffee cups, and water bottles. Shop products with less packaging. Meal prep. Cancel paper statements and other unnecessary mail subscriptions. And, instead of trashing your old belongings, donate your old clothes, toys, and furniture. **Thrifting is recycling** and reduces pollution and waste!
